name: Makefile CI

on:
  push:
    paths-exclude:
    - '.github/**'
    - '.gitignore'
    - 'README'
    - '**README'
    - 'LICENSE'
    - 'CMAKE**'
    - '**CMakeLists.txt'
  pull_request:
    paths-exclude:
    - '.github/**'
    - '.gitignore'
    - 'README'
    - '**README'
    - 'LICENSE'
    - 'CMAKE**'
    - '**CMakeLists.txt'

env:
  CFLAGS: "-Wall -pedantic"
  FFLAGS: "-fimplicit-none -fcheck=all"

defaults:
  run:
    shell: bash

jobs:

  build-all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ScaLAPACK
      uses: actions/checkout@v2
    - name: Install MPI
      run: sudo apt install mpich
    - name: Build ScaLAPACK
      run: |
        cp SLmake.inc.example SLmake.inc
        make --silent -j4 lib
        make --silent all
    - name: Run examples
      working-directory: ${{github.workspace}}/EXAMPLE
      run: |
        mpiexec -n 4 ./xsscaex
        mpiexec -n 4 ./xdscaex
        mpiexec -n 4 ./xcscaex
        mpiexec -n 4 ./xzscaex
